### ISSUE TITLE
Add a note on the guide regarding missing dependencies on Java versions newer than 1.8

### ISSUE THREAD

**Issue by Glomels** [Azure-Samples/ms-identity-java-webapi#11]
I was getting an error regarding bean instantiation via the factory method 'springSecurityFilterChain'.
Apparently this is just caused by missing JAXB dependencies, which are included in Java 8 but not in later versions.

I had to add these dependencies to get the obo sample to compile and run:

`<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
        </dependency>`

So maybe this should be added as a note on the guide, so developers are aware of this beforehand.

**Comment by idg-sam** [comment]
Thank you for raising this issue Glomels.
The dependencies have been updated to support versions of Java higher than 8 (1.8) in this PR: https://github.com/Azure-Samples/ms-identity-java-webapi/pull/14

Tested with Java 8, 11, 12, and 14.
